### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by efidiles** [efidiles/folder-template#6]
- [ ] Create an install command to setup predefined sets of templates (such as a set of templates for angular, ngrx, react etc)
- [ ] Create an example to demonstrate the usage of a handlebards `if` in templates
- [ ] Show to the user where the files will be created (also mention CTRL + C to cancel)
